const paragraphs=["The best races are not won by rushing. They are won by finding a rhythm, staying present, and letting every clean word move you forward.","Small improvements compound quickly when you make room for focus. One accurate sentence is the start of a much faster run.","A clear mind makes quick work. Read ahead, trust your hands, and keep the pace smooth from the first letter to the last.","There is a quiet joy in getting every word right. Speed follows attention, and attention turns practice into progress.","Good typing feels less like a sprint and more like a current. Set your line, catch the flow, and keep moving."];
const players=[{name:'you',wpm:0,points:0,cls:'current',initial:'YO'},{name:'mira',wpm:92,points:8,initial:'M'},{name:'alex',wpm:76,points:6,initial:'A'}];let round=1,startedAt,typed='',activePara=paragraphs[0];
const $=id=>document.getElementById(id);function renderBoard(){ $('playerCount').textContent=String(players.length).padStart(2,'0');$('leaderboard').innerHTML=players.map((p,i)=>`<div class="player ${p.cls||''}"><span class="rank">0${i+1}</span><span class="avatar ${p.name==='you'?'avatar-you':''}">${p.initial}</span><span class="p-name">${p.name}</span><span class="p-wpm"><b>${p.wpm||'—'}</b> wpm</span><span class="bar"><i style="width:${Math.min(100,(p.wpm||0)/1.2)}%"></i></span></div>`).join('');let avg=players.filter(p=>p.wpm).reduce((a,p)=>a+p.wpm,0)/(players.filter(p=>p.wpm).length||1);$('avgWpm').textContent=avg?Math.round(avg):'—'}renderBoard();
$('copyBtn').onclick=()=>{navigator.clipboard?.writeText('N8K4R');$('copyBtn').innerHTML='copied ✓'};
$('startBtn').onclick=startRace;document.addEventListener('keydown',e=>{if(e.key==='Enter'&&$('lobbyView').classList.contains('hidden')===false)startRace()});
function startRace(){ $('lobbyView').classList.add('hidden');$('raceView').classList.remove('hidden');$('roundLabel').textContent='race in progress';$('stageHint').textContent='syncing racers';activePara=paragraphs[round-1];$('prompt').textContent=activePara;$('countdown').classList.remove('hidden');let n=5;$('countdown').textContent=n;let t=setInterval(()=>{n--;if(n===0){clearInterval(t);$('countdown').classList.add('hidden');beginTyping()}else $('countdown').textContent=n},900)}
function beginTyping(){startedAt=Date.now();$('statusTag').textContent='RACING';$('typeInput').disabled=false;$('typeInput').focus();$('stageHint').textContent='type the paragraph';$('typeInput').oninput=updateTyping;let pins=players.map((p,i)=>`<div class="racer-pin ${p.name==='you'?'you':''}" id="pin-${p.name}" style="left:${i?18+i*18:3}%"><div class="racer-dot">${p.initial}</div><span class="racer-label">${p.name}</span></div>`).join('');$('raceTrack').innerHTML=pins;requestAnimationFrame(tick)}
function tick(){if(!$('raceView').classList.contains('hidden')){let sec=Math.floor((Date.now()-startedAt)/1000);$('timer').textContent=`00:${String(sec).padStart(2,'0')}`;requestAnimationFrame(tick)}}
function updateTyping(e){typed=e.target.value;let correct=0;for(let i=0;i<typed.length;i++)if(typed[i]===activePara[i])correct++;let acc=typed.length?Math.round(correct/typed.length*100):100;$('accuracy').textContent=acc+'%';let mins=(Date.now()-startedAt)/60000;$('liveWpm').textContent=Math.round((correct/5)/(mins||1));$('prompt').innerHTML=activePara.split('').map((c,i)=>i<typed.length?`<span class="${typed[i]===c?'':'wrong'}">${c}</span>`:c).join('');let progress=Math.min(92,Math.round(typed.length/activePara.length*90)+3);$('pin-you').style.left=progress+'%';if(typed.length>=activePara.length)finishRound()}
$('finishBtn').onclick=finishRound;function finishRound(){if(!startedAt)return;let w=Number($('liveWpm').textContent)||78;players[0].wpm=w;players[0].points=Math.max(1,Math.min(10,Math.round(Number($('accuracy').textContent.replace('%',''))/10)));renderBoard();$('raceView').classList.add('hidden');$('resultsView').classList.remove('hidden');$('roundLabel').textContent='round complete';$('stageHint').textContent='results are in';$('resultWpm').textContent=w;$('resultAccuracy').textContent=$('accuracy').textContent;$('resultRound').textContent=String(round).padStart(2,'0');$('resultGrid').innerHTML=[...players].sort((a,b)=>b.wpm-a.wpm).map((p,i)=>`<div class="result-row ${p.name==='you'?'you':''}"><span class="r-place">0${i+1}</span><span class="r-name">${p.name}${p.name==='you'?' (you)':''}</span><span class="r-wpm">${p.wpm||'—'} wpm</span><span class="r-points">+${p.points||0} pts</span></div>`).join('');startedAt=null}
$('nextBtn').onclick=()=>{round++;if(round>5){round=1;players.forEach(p=>p.points=0)}$('roundNumber').innerHTML=`round ${String(round).padStart(2,'0')} <i>/ 05</i>`;$('resultsView').classList.add('hidden');$('typeInput').value='';typed='';startRace()};
